// APPS/Angular/clientpanelfinal/src/app/components/add-client/add-client.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { Client } from '../../models/Client';
import { FlashMessagesService } from 'angular2-flash-messages';
import { ClientService } from '../../services/client.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-client',
  templateUrl: './add-client.component.html',
  styleUrls: ['./add-client.component.css']
})
export class AddClientComponent implements OnInit {

  // Properties
  client: Client = {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    balance: 0
  }
  disableBalanceOnAdd: boolean = true;
  @ViewChild('clientForm') from: any;


  constructor(
    private flashMessage: FlashMessagesService,
    private clientService: ClientService,
    private router: Router
  ) { }

  ngOnInit() {
  }

  onSubmit({ value, valid }: { value: Client, valid: boolean }) {
    if (this.disableBalanceOnAdd) {
      value.balance = 0;
    }
    if (!valid) {
      // @SHOW ERROR
      this.flashMessage.show("Please fill out the form correctly", {
        cssClass: 'alert-danger', timeout: 4000
      });
    } else {
      // @ADD NEW CLIENT
      this.clientService.newClient(value);
      // @SHOW MESSAGE
      this.flashMessage.show("New Client added", {
        cssClass: 'alert-success', timeout: 4000
      });
      // @REDIRECT TO DASH
      this.router.navigate(['/']);

    }
  }

}

<div class="row">
  <div class="col-md-6">
    <a routerLink="/" class="btn btn-link">
      <i class="fa fa-arrow-circle-o-left"></i> Back to Dashboard
    </a>
  </div>
  <div class="col-md-6">

  </div>
</div>

<div class="card">
  <div class="card-header">
    Add Client
  </div>
  <div class="card-body">
    <form #clientForm="ngForm" (ngSubmit)="onSubmit(clientForm)">
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" name="firstName" #clientFirstName="ngModel" [ngClass]="{'is-invalid':clientFirstName.errors && clientFirstName.touched}"
          [(ngModel)]="firstName" minlength="2" required>
        <div [hidden]="!clientFirstName.errors?.required" class="invalid-feedback">
          First Name Required
        </div>
        <div [hidden]="!clientFirstName.errors?.minlength" class="invalid-feedback">
          Must Be at least 2 characters
        </div>
      </div>
      <div class="form-group">
        <label for="firstName">Last Name</label>
        <input type="text" class="form-control" name="LastName" #clientLastName="ngModel" [ngClass]="{'is-invalid':clientLastName.errors && clientLastName.touched}"
          [(ngModel)]="lastName" minlength="2" required>
        <div [hidden]="!clientLastName.errors?.required" class="invalid-feedback">
          Last Name Required
        </div>
        <div [hidden]="!clientLastName.errors?.minlength" class="invalid-feedback">
          Must Be at least 2 characters
        </div>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" name="email" #clientEmail="ngModel" [ngClass]="{'is-invalid':clientEmail.errors && clientEmail.touched}"
          [(ngModel)]="email" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$" required>
        <div [hidden]="!clientEmail.errors?.required" class="invalid-feedback">
          Email Required
        </div>
        <div [hidden]="!clientEmail.errors?.pattern" class="invalid-feedback">
          Email is Invalid
        </div>
      </div>
      <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" name="phone" [ngClass]="{'is-invalid':clientPhone.errors && clientPhone.touched}"
          [(ngModel)]="client.phone" #clientPhone="ngModel" minlength="10" required>
        <div [hidden]="!clientPhone.errors?.required" class="invalid-feedback">
          Phone Required
        </div>
        <div [hidden]="!clientPhone.errors?.minlength" class="invalid-feedback">
          Must Be at least 10 digits
        </div>
      </div>
      <div class="form-group">
        <label for="balance">Balance</label>
        <input type="number" name="balance" class="form-control" [(ngModel)]="client.balance" #clientBalance="ngModel"
          [disabled]="disableBalanceOnAdd">
      </div>

      <input type="submit" value="Submit" class="btn btn-primary btn-block">
    </form>
  </div>
</div>

// APPS/React/react_clientpanel/src/components/clients/AddClient.js
import React, { Component } from 'react'
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { compose } from 'redux'
import { firestoreConnect } from 'react-redux-firebase'


class AddClient extends Component {
  state = {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    balance: ''
  }


  onSubmit = (e) => {
    e.preventDefault();

    const newClient = this.state;
    const { firestore, history } = this.props;

    // if no balance make it 0
    if (newClient.balance === '') {
      newClient.balance = 0;
    }

    firestore.add({ collection: 'clients' }, newClient).then(() => history.push('/'));
  }

  onChange = (e) => this.setState({
    [e.target.name]: e.target.value
  });

  render() {

    const { disableBalanceOnAdd } = this.props.settings;

    return (
      <div>
        <div className="row">
          <div className="col-md-6">
            <Link to="/" className="btn btn-link" >
              <i className="fas fa-arrow-circle-left"></i>  Back to Dashboard
            </Link>
          </div>
          <div className="col-md-6">

          </div>
        </div>
        <div className="card">
          <div className="card-header">Add Client</div>
          <div className="card-body">
            <form onSubmit={this.onSubmit}>
              <div className="form-group">
                <label htmlFor="firstName">First Name</label>
                <input
                  type="text"
                  className="form-control"
                  name="firstName"
                  minLength="2"
                  required
                  onChange={this.onChange}
                  value={this.state.firstName}
                />
              </div>
              <div className="form-group">
                <label htmlFor="lastName">Last Name</label>
                <input
                  type="text"
                  className="form-control"
                  name="lastName"
                  minLength="2"
                  required
                  onChange={this.onChange}
                  value={this.state.lastName}
                />
              </div>
              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  type="text"
                  className="form-control"
                  name="email"
                  onChange={this.onChange}
                  value={this.state.email}
                />
              </div>
              <div className="form-group">
                <label htmlFor="phone">Phone</label>
                <input
                  type="text"
                  className="form-control"
                  name="phone"
                  minLength="10"
                  required
                  onChange={this.onChange}
                  value={this.state.phone}
                />
              </div>
              <div className="form-group">
                <label htmlFor="balance">Balance</label>
                <input
                  type="text"
                  className="form-control"
                  name="balance"
                  onChange={this.onChange}
                  value={this.state.balance}
                  disabled={disableBalanceOnAdd}
                />
              </div>

              <input
                type="submit"
                value="Submit"
                className="btn btn-primary btn-block"
              />
            </form>
          </div>
        </div>
      </div>
    );
  }
}

AddClient.propTypes = {
  firestore: PropTypes.object.isRequired,
  settings: PropTypes.object.isRequired
};

export default compose(
  firestoreConnect(),
  connect((state, props) => ({
    settings: state.settings
  }))
)(AddClient);
